from random import randint

##Generate Random Number##
x = randint(0, 99)

##Challenges in array##
challenges = ["Name Generator", "Higher/Lower", "Temperature Converter", "Calculate age in seconds", "Encryption/Decryption Algorithm", "FizzBuzz", "Rock, Paper, Scizzors", "Project Euler", "Hangman", "Love Calculator", "Random Sentence Generator", "Password Generator", "Internet Time", "Haiku Generator", "Magic Eight Ball", "Collatz Conjecture", "Reverse a String", "Eulerian Path", "Simple File Explorer", "Count Words in a String", "Minesweeper", "Connect 4", "BMI Calculator", "4chan thread downloader", "Sudoku Generater/Solver", "Maze Generater/Solver", "Radix Converter", "Picross Solver", "Fibonacci Sequence", "Factorial", "Cipher Encryption/Decryption Tool", "Blackjack", "Dungeons and Dragons with AI", "Generate ASCII Tree", "Genetic Algorithms on Polygons", "Benford's Law", "Currency Converter", "Static Website Generator", "Crossword Game", "Scientific Calculator", "Perlin Noise", "Image Viewer", "ASCII Digital Clock", "Dijkstra's Algorithm" , "Text/Morse code translator", "Tic-Tac-Toe", "Snake Game", "FTP Client", "Telnet Server", "IMP Interpreter", "Tetris", "Conway's Game of Life", "Web Crawler", "Text Editor", "RSS Feed Reader", "RPN Calculator", "Mandelbrot Set", "Sorting Algorithms", "Custom Markup -> HTML Converter", "N Queens Problem", "Flow in a Network", "Credential Validator", "Linked List", "Mastermind", "Random Image Generator", "Ulam Spiral", "Klingon Translator", "Prime Number Generator", "Markov Chains", "Graphical Analog Clock", "Two Languages Communicating", "Triangle Number Calculator", "Typing Speed Calculator", "Name Art in ASCII", "Towers of Hanoi", "Quine", "IRC Bot", "Brainfuck Interpreter", "Chip-8 Emulator", "Geekcode Generator", "Define, Translate, and Rotate a Polygon", "Pong with variable vectors", "Battleships with AI", "Simple Paint Program", "TCP Chat with basic encryption", "Incremental Economy Simulator", "Encrypting Data in Images", "Pascal's Trangle", "Sine Wave Generator from Pseudorandom numbers", "Flappy Bird", "Fourier Transformation", "Method Ringing Simulator", "Binary Search", "Nintendo Oil Panic", "Sierpinski Triangle", "Dot and Cross Product of Two Vectors", "Little Man computer simulation", "Lisp Interpreter", "Enigma Simulator with a Configuration File"]

##Print Challenge##
print(challenges[x])
